function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 28-Mar-2018 14:28:31

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 1000;  % Passband Frequency
    % Fstop = 2000;  % Stopband Frequency
    % Apass = 1;     % Passband Ripple (dB)
    % Astop = 80;    % Stopband Attenuation (dB)
    % Fs    = 8192;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'stopband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.2147187215227 0.8226352371346; 1 2 1 1 ...
        -1.03705005613104 0.556050747787483; 1 2 1 1 -0.916821713829899 ...
        0.375653089220359; 1 2 1 1 -0.837540994224741 0.256695646137065; 1 2 1 1 ...
        -0.789279735192294 0.184281621604082; 1 2 1 1 -0.766419262204284 ...
        0.149980426712411], ...
        'ScaleValues', [0.151979128902975; 0.12975017291411; ...
        0.114707843847615; 0.104788662978081; 0.0987504716029469; ...
        0.0958902911270318; 1]);
end

s = double(x);
y = step(Hd,s);

